version: '3.8'

services:
  vtol_mission:
    build:
      context: .
    image: seyeongw/vtol_mission:dev
    container_name: vtol_mission_dev
    network_mode: "bridge"

    command: >
      bash -c "source /ros2_ws/install/setup.bash &&
      ros2 launch vtol_mission takeoff.launch.py"